<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

include_once "header.php";
include_once "db.php";
include '_Layout.php';

if(isset($_GET['id'])){
	$id = $_GET['id'];
	$data = array();
	$query = "SELECT * FROM `details` WHERE id='".$id."'";
	$select_res = mysqli_query($con, $query);

	while($row=mysqli_fetch_array($select_res, MYSQLI_ASSOC)){
		$data[] = $row; 
	}

	echo "<table>";
	echo "<tr>";
	echo "<td style=\"vertical-align:top\">";
	//first table
	echo "<table class=\"table table-bordered\">";
	echo "<thead>";
	echo "<tr>";
	echo "<th colspan=2>Employee Detail</th>";
	echo "</tr>";
	echo "</thead>";
	//while ($row = mysqli_fetch_assoc( $select_res )){
	$row = mysqli_fetch_assoc( $select_res )
		echo "<tr>";
		echo "	<td>Employee No</td>";
		echo "	<td>".$row['EMPNUMBER']."</td>";
		echo "</tr>";
		echo "<tr>";
		echo "	<td>Employee Name</td>";
		echo "	<td>".$row['EMPNAME']."</td>";
		echo "</tr>";
		echo "<tr>";
		echo "	<td>DESIGNATION</td>";
		echo "	<td>".$row['DESIGNATION']."</td>";
		echo "</tr>";
		echo "<tr>";
		echo "	<td>DEPARTMENT NAME</td>";
		echo "	<td>".$row['DEPT_NAME']."</td>";
		echo "</tr>";
		echo "<tr>";
		echo "	<td>DATE OF JOINING</td>";
		echo "	<td>".$row['EMP_DOJ']."</td>";
		echo "</tr>";
		echo "<tr>";
		echo "	<td>DATE OF BIRTH</td>";
		echo "	<td>".$row['EMP_DOB']."</td>";
		echo "</tr>";
		echo "<tr>";
		echo "	<td>ACC NUMBER</td>";
		echo "	<td>".$row['ACCOUNT_NUMBER']."</td>";
		echo "</tr>";
		echo "<tr>";
		echo "	<td>GENDER</td>";
		echo "	<td>".$row['EMP_GENDER']."</td>";
		echo "</tr>";
	//}

	echo "</table>";
	echo "</td>";

	echo "<td style=\"vertical-align:top\">";
	//second table


	echo "<table class=\"table table-bordered\">";

	echo "<thead>";
	echo "<tr>";
	echo "<th colspan=2>Employee Salary Detail</th>";
	echo "</tr>";
	echo "</thead>";
	while ($data){
	echo "<tr>";
	echo "	<td>PF INDEX</td>";
	echo "	<td>".$row['PF_INDEX']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>NEW JOINEE</td>";
	echo "	<td>".$row['NEW_JOINEE']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>PROMOTION</td>";
	echo "	<td>".$row['PROMOTION']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>RESIGNEE</td>";
	echo "	<td>".$row['RESIGNEE']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>TRANSFER</td>";
	echo "	<td>".$row['TRANSFER']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>EMP TRANSFER DT</td>";
	echo "	<td>".$row['EMP_TRANSFER_DT']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>EMP TERMINATION DT</td>";
	echo "	<td>".$row['EMP_TERMINATION_DT']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>EMP PROMOTION DT</td>";
	echo "	<td>".$row['EMP_PROMOTION_DT']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>EMP PAY SCALE</td>";
	echo "	<td>".$row['EMP_PAY_SCALE']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>PAID DAYS</td>";
	echo "	<td>".$row['PAID_DAYS']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>BASIC</td>";
	echo "	<td>".$row['BASIC']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>D.A</td>";
	echo "	<td>".$row['D.A']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>CON ALL</td>";
	echo "	<td>".$row['CON_ALL']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>HRA</td>";
	echo "	<td>".$row['HRA']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>SP ALL</td>";
	echo "	<td>".$row['SP_ALL']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>BONUS</td>";
	echo "	<td>".$row['BONUS']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>EDU ALL</td>";
	echo "	<td>".$row['EDU_ALL']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>CCA</td>";
	echo "	<td>".$row['CCA']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>MED ALL</td>";
	echo "	<td>".$row['MED_ALL']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>OTH ALL</td>";
	echo "	<td>".$row['OTH_ALL']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>PTAX</td>";
	echo "	<td>".$row['PTAX']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>ITAX</td>";
	echo "	<td>".$row['ITAX']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>EPF</td>";
	echo "	<td>".$row['EPF']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>LIC</td>";
	echo "	<td>".$row['LIC']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>CREDIT SOC LN</td>";
	echo "	<td>".$row['CREDIT_SOC_LN']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>HSG LN1</td>";
	echo "	<td>".$row['HSG_LN1']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>HSG LN2</td>";
	echo "	<td>".$row['HSG_LN2']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>HSG LN3</td>";
	echo "	<td>".$row['HSG_LN3']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>HSG REP LN1</td>";
	echo "	<td>".$row['HSG_REP_LN1']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>HSG REP LN2</td>";
	echo "	<td>".$row['HSG_REP_LN2']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>HSG EXT LN</td>";
	echo "	<td>".$row['HSG_EXT_LN']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>VEH LN</td>";
	echo "	<td>".$row['VEH_LN']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>FURNT LN1</td>";
	echo "	<td>".$row['FURNT_LN1']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>FURNT LN2</td>";
	echo "	<td>".$row['FURNT_LN2']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>FMY CAR LN</td>";
	echo "	<td>".$row['FMY_CAR_LN']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>EDU LOAN1</td>";
	echo "	<td>".$row['EDU_LOAN1']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>EDU LOAN2</td>";
	echo "	<td>".$row['EDU_LOAN2']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>OTH DED 1</td>";
	echo "	<td>".$row['OTH_DED_1']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>OTH DED 2</td>";
	echo "	<td>".$row['OTH_DED_2']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>ECOD INT</td>";
	echo "	<td>".$row['ECOD_INT']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>GROSS EARNING</td>";
	echo "	<td>".$row['GROSS_EARNING']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>TOTAL DEDUCTION</td>";
	echo "	<td>".$row['TOTAL_DEDUCTION']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>NET SALARY PAYABLE</td>";
	echo "	<td>".$row['NET_SALARY_PAYABLE']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>UPDATE DATE</td>";
	echo "	<td>".$row['UPDATE_DATE']."</td>";
	echo "</tr>";
	echo "<tr>";
	echo "	<td>PAYSLIPS REMARKS</td>";
	echo "	<td>".$row['PAYSLIPS_REMARKS']."</td>";
	echo "</tr>";
	}
	echo "</table>";
	echo "</td>";

	echo "</tr>";
	echo "</table>";
}
